### ISSUE TITLE
Many error since last update

### ISSUE THREAD

**Issue by Gnomexpress** [kemayo/wow-handynotes-secretfish#1]
Message: Interface/AddOns/HandyNotes_SecretFish/nodes.lua:22: attempt to call field 'RegisterPoints' (a nil value)
Time: Sun Nov 20 04:24:44 2022
Count: 1
Stack: Interface/AddOns/HandyNotes_SecretFish/nodes.lua:22: attempt to call field 'RegisterPoints' (a nil value)
[string "@Interface/AddOns/HandyNotes_SecretFish/nodes.lua"]:22: in main chunk

Locals: myname = "HandyNotes_SecretFish"
ns = <table> {
 defaultsOverride = <table> {
 }
 hiddenConfig = <table> {
 }
}
ANYWHERE = "Anywhere in this zone"
goggles = <table> {
 achievement = 13489
 atlas = "worldquest-icon-fishing"
 loot = <table> {
 }
}
(*temporary) = nil
(*temporary) = 946
(*temporary) = <table> {
 53004750 = <table> {
 }
}
(*temporary) = "attempt to call field 'RegisterPoints' (a nil value)"

--------------------------------------------------------------------------------------------------------------------------------------------

Message: Interface\FrameXML\Bindings.xml:16 Couldn't open Interface/AddOns/HandyNotes_SecretFish/handler/handler.xml
Time: Sun Nov 20 04:25:01 2022
Count: 1

--------------------------------------------------------------------------------------------------------------------------------------------

Message: Interface/AddOns/HandyNotes_SecretFish/nodes.lua:1 (null)
Time: Sun Nov 20 04:25:01 2022
Count: 1

--------------------------------------------------------------------------------------------------------------------------------------------

Message: Interface\FrameXML\Bindings.xml:1 Interface\FrameXML\Bindings.xml:16 Couldn't open Interface/AddOns/HandyNotes_SecretFish/handler/handler.xml
Time: Sun Nov 20 04:25:01 2022
Count: 1

--------------------------------------------------------------------------------------------------------------------------------------------

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/HandyNotes_SecretFish/nodes.lua:1 (null)
Time: Sun Nov 20 04:25:01 2022
Count: 1

--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Gnomexpress** [comment]
folder handler non available in your last build

**Comment by kemayo** [comment]
...yup, that build has indeed failed to package it. Give me a second to work out what went wrong.

**Comment by kemayo** [comment]
Okay, fixed the build and rereleasing things. Thanks for letting me know!
